# 1:SERVER CONFIGS ================================================== >
server.port=3000

# 2:APPLICATION CONFIGS ========================================= >
spring.application.name=hrm-system
spring.jackson.default-property-inclusion=non_empty

# 3:DB CONFIGS =================================================== >
spring.datasource.url=jdbc:postgresql://localhost:5432/hrm_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4:SWAGGER CONFIGS============================================ >
# Custom path for swagger UI
springdoc.swagger-ui.path=/api-docs
# Custom path for raw JSON
springdoc.api-docs.path=/v3/api-docs
# Sort endpoints alphabetically
springdoc.swagger-ui.operations-sorter=alpha